# Generated by Django 3.1.7 on 2021-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subcategory',
            field=models.CharField(default='cloud storage', max_length=50),
            preserve_default=False,
        ),
    ]
