# Generated by Django 3.1.7 on 2021-03-09 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='date_finished',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='report_url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='rightans_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='wrongans_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
