# Generated by Django 3.1.7 on 2021-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='sbu',
            field=models.CharField(default='SBU 1', max_length=40),
            preserve_default=False,
        ),
    ]
